# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  containerRegistry: '19eea2be-7bf2-46b9-b811-c43de32d2911'
  repository: 'milo/pro'
  acr_address: 'miloml.azurecr.io'

jobs:
- job: Functions
  condition: and(succeeded(), eq(variables.isMaster, 'true'))
  steps:
  - script: |
      npm --prefix functions install
    displayName: 'Install dependencies'

  - script: |
      npm --prefix functions run compile
    displayName: 'Build Firebase functions'

  - task: ArchiveFiles@2
    displayName: 'Create Firebase artifact'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/functions'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/payload.zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Firebase functions artifact'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/payload.zip' 
      artifactName: 'functions'

- job: AutoML
  condition: and(succeeded(), eq(variables.isMaster, 'true'))
  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pip install pytest pytest-azurepipelines
      pytest
    displayName: 'ML Module Unit Test'

- job: Docker
  steps:
  - checkout: self
    submodules: true

  - task: NodeTool@0
    inputs:
      versionSpec: '16'
    
  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: $(knownHostsEntry)
      sshPublicKey: $(sshPublicKey)
      sshKeySecureFile: 'id_rsa'

  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.x'
    displayName: 'Install GitVersion'

  - task: gitversion/execute@0
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)'
    displayName: 'Run GitVersion'

  - script: |
      sed -i.bak "s|\"version\": \"[0-9\.]*\"|\"version\": \"$GITVERSION_MAJORMINORPATCH\"|" package.json
    displayName: 'Update package version'

  - task: Docker@2
    inputs:
      containerRegistry: '$(containerRegistry)'
      command: 'login'
    displayName: Login to ACR
  
  - script: 'docker pull $(acr_address)/$(repository):latest'
    displayName: Pull latest for layer caching
    continueOnError: true

  - script: |
      npm --prefix ui ci --cache $(Pipeline.Workspace)/.npm
      npm --prefix docs ci --cache $(Pipeline.Workspace)/.npm
      npm --prefix preprocessor ci --cache $(Pipeline.Workspace)/.npm
    displayName: 'Install dependencies'

  - script: |
      npm --prefix ui run build-docker
    displayName: 'Build Angular SPA'

  - script: |
      npm --prefix docs run build
    displayName: 'Build Documentation'

  - script: |
      npm --prefix preprocessor run milo-build
    displayName: 'Build Preprocessor'

  - task: Docker@2
    inputs:
      command: build
      repository: '$(repository)'
      tags: latest
      dockerfile: '**/Dockerfile'
      containerRegistry: '$(containerRegistry)'
      arguments: '--cache-from=$(acr_address)/$(repository):latest' 
    displayName: Build Docker Image

  - task: Docker@2
    displayName: Push Docker Image to ACR
    inputs:
      command: push
      containerRegistry: '$(containerRegistry)'
      repository: '$(repository)' 
      tags: latest

  - script: |
      pip install requests Flask licensing
      npm run generate-education-license
    displayName: Create Education License

  - task: Docker@2
    inputs:
      command: build
      repository: 'milo/education'
      tags: latest
      dockerfile: '**/Dockerfile'
      containerRegistry: '$(containerRegistry)'
      arguments: '--cache-from=$(acr_address)/$(repository):latest' 
    displayName: Build Education Docker Image

  - task: Docker@2
    displayName: Push Education Docker Image to ACR
    inputs:
      command: push
      containerRegistry: '$(containerRegistry)'
      repository: 'milo/education'
      tags: latest

  - task: CopyFiles@2
    displayName: 'Copy Firebase configuration to staging'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
        firebase.json
        firestore.rules
        firestore.indexes.json
      TargetFolder: '$(Build.ArtifactStagingDirectory)/firebase'

  - task: CopyFiles@2
    displayName: 'Copy SPA to staging'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/static'
      Contents: '**'
      TargetFolder: '$(build.ArtifactStagingDirectory)/firebase/static'

  - task: ArchiveFiles@2
    displayName: 'Create Firebase artifact'
    inputs:
      rootFolderOrFile: '$(build.ArtifactStagingDirectory)/firebase'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/payload.zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Firebase hosting artifact'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/payload.zip' 
      artifactName: 'static'
