name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Hosting Artifact
        uses: actions/download-artifact@v3
        with:
          name: static
          run-id: ${{ github.event.workflow_run.id }}

      - name: Extract Hosting Files
        run: unzip payload.zip -d .

      - name: Download Functions Artifact
        uses: actions/download-artifact@v3
        with:
          name: functions
          run-id: ${{ github.event.workflow_run.id }}

      - name: Extract Functions Files
        run: unzip functions/payload.zip -d functions

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Functions Dependencies
        run: npm --prefix functions install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy --project milo-ml --message "Release: ${{ github.run_number }}"
